[build]
target-dir = "target"

[target.x86_64-unknown-none]
linker = "rust-lld"
rustflags = [
  "-C", "link-arg=--script=./linker/x86_64.ld",
]

[target.aarch64-unknown-none]
linker = "rust-lld"
rustflags = [
  "-C", "link-arg=--script=./linker/aarch64.ld",
]