# ===============================================================================
# RustFoundry OS:
# Developer-first OS built in Rust, including console-only "Bare Metal Edition".
# Copyright (C) 2025 XalorTech
# License: GPLv3 (see LICENSE.md for details)
# ===============================================================================

[build]
target-dir = "target"

[target.x86_64-unknown-none]
linker = "rust-lld"
rustflags = [
	"-C", "link-arg=-nostartfiles",
	"-C", "link-arg=-nodefaultlibs",
]

[target.aarch64-unknown-none]
linker = "rust-lld"
rustflags = [
	"-C", "link-arg=-nostartfiles",
	"-C", "link-arg=-nodefaultlibs",
]
